name: price_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  json_annotation: ^4.7.0
  dio: ^4.0.6
  auto_size_text: ^3.0.0
  freezed_annotation: ^2.1.0
  pretty_dio_logger: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  get_it: ^7.2.0
  go_router: ^4.5.1
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  http_mock_adapter: ^0.3.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  freezed: ^2.1.1
  flutter_gen_runner: ^4.3.0
  hive_generator: ^1.1.3

dependency_overrides:
  analyzer: ^4.7.0

flutter:
  uses-material-design: true
